/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package chat_room;

import org.junit.Test;
import static org.junit.Assert.*;

public class MainTest {
    @Test public void testMainClass() {
    }
}
